"""Image generation tool for Waypoint Concierge using gemini-3.1-flash-lite-image."""

import re
import time
import uuid
from typing import Any
from google import genai
from google.genai import types
from google.cloud import storage
from google.adk.tools import ToolContext

# Hardcoded bucket name and project ID string
BUCKET_NAME = "waypoint-concierge-media-793c4b"
GCP_PROJECT_ID = "qwiklabs-gcp-04-793c4bc8c9f7"
MODEL_NAME = "gemini-3.1-flash-lite-image"
MODEL_LOCATION = "global"

_genai_client: genai.Client | None = None
_storage_client: storage.Client | None = None


def _get_genai_client() -> genai.Client:
    global _genai_client
    if _genai_client is None:
        _genai_client = genai.Client(
            vertexai=True,
            project=GCP_PROJECT_ID,
            location=MODEL_LOCATION,
        )
    return _genai_client


def _get_storage_client() -> storage.Client:
    global _storage_client
    if _storage_client is None:
        _storage_client = storage.Client(project=GCP_PROJECT_ID)
    return _storage_client


def generate_destination_image(
    prompt: str,
    tool_context: ToolContext,
) -> dict[str, Any]:
    """Generate a scenic travel image or postcard for a destination, attraction, or itinerary item.

    Args:
        prompt: Detailed visual prompt describing the scene, mood, lighting, and destination (e.g., 'A scenic postcard of Fushimi Inari shrine with vermilion torii gates at sunrise').

    Returns:
        A dictionary containing the image's public Cloud Storage URL and artifact filename.
    """
    try:
        client = _get_genai_client()

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                response_modalities=["IMAGE"],
            ),
        )

        if not response.candidates or not response.candidates[0].content.parts:
            return {"error": "No image was generated by the model."}

        part = response.candidates[0].content.parts[0]
        if not part.inline_data or not part.inline_data.data:
            return {"error": "Generated content did not contain image data."}

        image_bytes = part.inline_data.data
        mime_type = part.inline_data.mime_type or "image/jpeg"
        ext = "png" if "png" in mime_type.lower() else "jpg"

        slug = re.sub(r"[^a-zA-Z0-9]+", "_", prompt[:30]).strip("_").lower()
        unique_suffix = f"{int(time.time())}_{uuid.uuid4().hex[:6]}"
        filename = f"{slug}_{unique_suffix}.{ext}" if slug else f"image_{unique_suffix}.{ext}"

        # 1. Save artifact for the Playground's Artifacts panel
        if tool_context:
            artifact_part = types.Part.from_bytes(data=image_bytes, mime_type=mime_type)
            tool_context.save_artifact(
                filename=filename,
                artifact=artifact_part,
            )

        # 2. Upload image bytes directly to the public Cloud Storage bucket
        storage_cli = _get_storage_client()
        bucket = storage_cli.bucket(BUCKET_NAME)
        blob = bucket.blob(filename)
        blob.upload_from_string(image_bytes, content_type=mime_type)

        public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/{filename}"

        return {
            "prompt": prompt,
            "filename": filename,
            "public_url": public_url,
            "artifact_saved": True,
            "message": f"Image generated successfully. Available publicly at {public_url}",
        }
    except Exception as e:
        return {"error": f"Failed to generate destination image: {str(e)}"}
